blockchains:
  hello:
    module: main
    moduleArgs:
      main:
        admin_key: 031b84c5567b126440995d3ed5aaba0565d71e1834604819ff9c17f5e9d5dd078f
compile:
  rellVersion: 0.12.0
test:
  modules:
    - test.arithmetic_test
    - test.data_test
